### ISSUE TITLE
thinking about reset time

### ISSUE THREAD

**Issue by denis1011101** [denis1011101/super_cm_bot#8]
Сань я чёт задумался, [сейчас](https://github.com/denis1011101/super_cm_bot/blob/main/app/handlers/handlers_helper.go#L18) можно крутить спин каждые 4 часа

```go
func checkIsSpinNotLegal(lastUpdate time.Time) bool {
	if !lastUpdate.IsZero() {
		duration := time.Since(lastUpdate)
		lastUpdateIsToday := compareTimesByDate(time.Now(), lastUpdate)

		if duration.Hours() < 4 && lastUpdateIsToday {
			log.Println("Spin is not legal: less than 4 hours since last update and it's today")
			return true
		}
	}
	log.Println("Spin is legal")
	return false
}

func compareTimesByDate(a, b time.Time) bool {
	return a.Year() == b.Year() &&
		a.Month() == b.Month() &&
		a.Day() == b.Day()
}
```

а в оригинале было

```php
<?php
public function needSkipSpinPidor(int $chatId): bool
{
    $date = $this->pidorsRepository->getLastPidorDateTime($chatId);

    if ($date === null) {
        return false;
    }

    $currentDateTime = new DateTimeImmutable();

    return $date->format('d') === $currentDateTime->format('d');
}
```

наверное правильнее проверять если следующий день то разрешать крутить, так?

**Comment by Keklil** [comment]
Почему там же двойная проверка: менее 4 часов с прошлого спина и что день спина совпадает с текущим -> тогда не даём крутить. Я этот лаг в 4 часа сделал, чтоб нельзя было в 23.59 покрутить и потом сразу в 00.00.

**Comment by Keklil** [comment]
Там же тест на это ещё есть, все ок

**Comment by denis1011101** [comment]
ну так что Саныч, не против чтобы не каждые четыре часа можно было вызывать бота, а раз в сутки, но чтобы не сразу после 00.00, например через 4 часа? лучше же будет?

**Comment by denis1011101** [comment]
хотя ладно. я подумал, особенность у нас такая, не во всём же следовать оригиналу, пусть каждые 4 часа будет можно

**Comment by Keklil** [comment]
Так сейчас так и работает - раз в сутки и не чаще чем, раз в 4 часа

**Comment by Keklil** [comment]
Я попозже ещё раз на код и тест взгляну, но там и так уже такая логика должна быть

**Comment by Keklil** [comment]
Кстати, а сервак в ютс живёт?

**Comment by denis1011101** [comment]
так Саныч мы когда для теста меняем часы на секунды то каждые 4 секунды можно крутить, сервак по классике в ютц живёт угу, но ваще мне уже нравится текущая логика, я проверил, работает приятно, хотят крутить каждые 4 часа - пусть крутят, быстрее обнулит 🤡

**Comment by Keklil** [comment]
давай тогда выкинем нафиг проверку с датой?

**Comment by denis1011101** [comment]
да давай, нифига я проглядел две недели назад лол
